# Generated by Django 5.0.6 on 2024-05-25 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('LG', 'Lamborghini Gallardo'), ('FR', 'Ferrari'), ('BM', 'BMW'), ('AU', 'Audi'), ('MB', 'Mercedes Benz')], max_length=2)),
            ],
        ),
    ]
