# Generated by Django 5.0.6 on 2024-06-01 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_firstvariety_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='firstVarietyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifcate_number', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expired', models.DateTimeField(default=django.utils.timezone.now)),
                ('first', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='first.firstvariety')),
            ],
        ),
        migrations.CreateModel(
            name='firstVarietyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstvariety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='first.firstvariety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='firstVarietyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('first_varieties', models.ManyToManyField(related_name='stores', to='first.firstvariety')),
            ],
        ),
    ]
