# Generated by Django 5.0.6 on 2024-06-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_firstvarietycertificate_firstvarietyreview_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='firstVarietyStore',
            new_name='Store',
        ),
    ]
